MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [91.488, 96.539, 89.642] 
  PIXEL_STD: [57.424, 55.494, 53.773] 
  RESNETS:
    DEPTH: 50 
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  TRAIN: ("lados_train",)
  TEST: ("lados_test",) 
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001 # 0.00001 en la prueba que volvi√≥ a dar menos de 40
  STEPS: (327778, 355092)
  MAX_ITER: 61750 # para batch de 6 son 20500
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 61750
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 1024 
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB" 
  DATASET_MAPPER_NAME: "mask_former_semantic_RAWB"
  MAX_SIZE_TEST: 680 # Originalmente 1333 y 800 # Para resnet 2000 y 1500 # Para SWIN 1800 y 1400
  MAX_SIZE_TRAIN: 680
  MIN_SIZE_TEST: 680
  MIN_SIZE_TRAIN:
  - 680
TEST: 
  EVAL_PERIOD: 618 
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4 
VERSION: 2
OUTPUT_DIR: ./output_LADOS_M2F_Standard_NOBRA
