_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3 
    PATCH_NORM: True
  WEIGHTS: "./backbone_weights/custom_pkls/swin_18_epochs.pkl"
  PIXEL_MEAN: [124.525, 91.488, 96.539, 89.642] #[124.525, 91.488, 96.539, 89.642] #[91.488, 96.539, 89.642]
  PIXEL_STD: [60.935, 57.424, 55.494, 53.773] #[60.935, 57.424, 55.494, 53.773] # [57.424, 55.494, 53.773]
