_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer" # "D2SwinTransformer" and "D2SwinTransformerFusionCNN" "D2SwinTransformerFusionCNNWithAttention" "D2DualSwinTransformerFusion" 
  SWIN: # "D2SwinTransformerFusionCNNWeightedSum" "D2SwinTransformerSEBlockFusionCNN" "D2SwinTransformerCNNChannelReduction" "D2ConvNeXt" "D2TIMMConvNeXt"
    EMBED_DIM: 96 # 96 Original: Si usas 192, no se aprovechan los pesos preentrenados del backbone
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  WEIGHTS: "./backbone_weights/swin_tiny_patch4_window7_224.pkl" #"./backbone_weights/swin_tiny_patch4_window7_224.pkl"
  PIXEL_MEAN: [124.525, 91.488, 96.539, 89.642, 90.000] # [124.525, 91.488, 96.539, 89.642]
  PIXEL_STD: [60.935, 57.424, 55.494, 53.773, 54.000] # [60.935, 57.424, 55.494, 53.773]
