MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl" # "/home/pablo.canosa/wip/python_notebooks/ResnetWeightConversion/R-50_S2_correct_stem_bands.pkl" #"/home/pablo.canosa/wip/python_notebooks/ResnetWeightConversion/R-50_S2+1.pkl" #"/home/pablo.canosa/wip/python_notebooks/ResnetWeightConversion/R-50_S2.pkl" #"detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [124.525, 91.488, 96.539, 89.642]  #[124.525, 91.488, 96.539, 89.642] 
  PIXEL_STD: [60.935, 57.424, 55.494, 53.773] #[60.935, 57.424, 55.494, 53.773] 
  RESNETS:
    DEPTH: 50 
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  TRAIN: ("gaofen_train",)
  TEST: ("gaofen_test",) 
SOLVER:
  IMS_PER_BATCH: 5
  BASE_LR: 0.0001 
  STEPS: (327778, 355092)
  MAX_ITER: 504000 # 316250 # 630000 es para batch de 4
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"  
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 504000 # CUANDO SE HAGAN EJECUCIONES IMPORTANTES DEJARLO A 2000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 1024 
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB" ## NOT USED
  DATASET_MAPPER_NAME: "mask_former_semantic_RAWB" 
  MAX_SIZE_TEST: 600 # Originalmente 1333 y 800 # Para resnet 2000 y 1500 # Para SWIN 1800 y 1400 # para GID de Francisco emplear  600 y 500
  MAX_SIZE_TRAIN: 600
  MIN_SIZE_TEST: 500
  MIN_SIZE_TRAIN:
  - 500
TEST: 
  EVAL_PERIOD: 5040
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4  
VERSION: 2
OUTPUT_DIR: ./pruebas_cambio_pixel_decoder_dataset_Francisco
SEED: 666
